version: '3' 

services:
  angular-service: 
    container_name: foodbox-angular1
    build: ./
    volumes: 
    - './:/usr/src/app'
    ports: 
      - "4200:4200"
    command: >
     bash -c "npm start"